[package]
name = "polkadot-service"
version = "0.5.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
parking_lot = "0.7.1"
lazy_static = "1.0"
log = "0.4.6"
slog = "^2"
tokio = "0.1.7"
hex-literal = "0.2"
av_store = { package = "polkadot-availability-store", path = "../availability-store" }
consensus = { package = "polkadot-validation", path = "../validation" }
polkadot-primitives = { path = "../primitives" }
polkadot-runtime = { path = "../runtime" }
polkadot-executor = { path = "../executor" }
polkadot-network = { path = "../network"  }
sr-io = { git = "https://github.com/paritytech/substrate", branch = "bkchr-cumulus-branch" }
sr-primitives = { git = "https://github.com/paritytech/substrate", branch = "bkchr-cumulus-branch" }
primitives = { package = "substrate-primitives", git = "https://github.com/paritytech/substrate", branch = "bkchr-cumulus-branch" }
client = { package = "substrate-client", git = "https://github.com/paritytech/substrate", branch = "bkchr-cumulus-branch" }
aura = { package = "substrate-consensus-aura", git = "https://github.com/paritytech/substrate", branch = "bkchr-cumulus-branch" }
consensus_common = { package = "substrate-consensus-common", git = "https://github.com/paritytech/substrate", branch = "bkchr-cumulus-branch" }
grandpa = { package = "substrate-finality-grandpa", git = "https://github.com/paritytech/substrate", branch = "bkchr-cumulus-branch" }
inherents = { package = "substrate-inherents", git = "https://github.com/paritytech/substrate", branch = "bkchr-cumulus-branch" }
service = { package = "substrate-service", git = "https://github.com/paritytech/substrate", branch = "bkchr-cumulus-branch" }
telemetry = { package = "substrate-telemetry", git = "https://github.com/paritytech/substrate", branch = "bkchr-cumulus-branch" }
transaction_pool = { package = "substrate-transaction-pool", git = "https://github.com/paritytech/substrate", branch = "bkchr-cumulus-branch" }
substrate-keystore = { git = "https://github.com/paritytech/substrate", branch = "bkchr-cumulus-branch" }
